from __future__ import annotations


LIVE_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>GPT Live Spectator</title>
<style>
:root{--bg:#efe6d3;--ink:#1f1b17;--muted:#5f5548;--panel:rgba(255,249,240,.92);--panel2:#f7efe2;--line:rgba(74,56,34,.18);--accent:#b24a2a;--shadow:0 16px 40px rgba(63,39,18,.12)}
*{box-sizing:border-box}body{margin:0;font-family:"Segoe UI","Malgun Gothic",sans-serif;color:var(--ink);background:radial-gradient(circle at top left,rgba(255,255,255,.45),transparent 28%),linear-gradient(180deg,#f4ecde 0%,#eadfc8 48%,#dfcfb2 100%)}
.page{min-height:100vh;padding:18px}.grid{display:grid;grid-template-columns:280px minmax(0,1fr) 320px;gap:16px;min-height:calc(100vh - 36px)}.col,.main{min-height:0}.col,.main{display:flex;flex-direction:column;gap:16px}
.panel{background:var(--panel);border:1px solid var(--line);border-radius:20px;box-shadow:var(--shadow);overflow:hidden}.head{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:14px 16px;background:linear-gradient(180deg,rgba(255,255,255,.8),rgba(255,255,255,.28));border-bottom:1px solid var(--line)}.body{padding:14px 16px 16px}
.eyebrow{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.08em}.title{margin:2px 0 0;font-size:24px}.meta,.helper{color:var(--muted);font-size:12px;line-height:1.45}
.chip,.mini{display:inline-flex;align-items:center;gap:6px;min-height:28px;padding:6px 10px;border-radius:999px;border:1px solid var(--line);background:rgba(255,255,255,.75);color:var(--muted);font-size:12px}.mini strong{color:var(--ink)}
.stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.stat{padding:12px;border-radius:16px;background:var(--panel2);border:1px solid var(--line)}.stat .k{color:var(--muted);font-size:12px}.stat .v{margin-top:6px;font-size:22px;font-weight:700}
.controls{display:flex;flex-wrap:wrap;gap:8px}.ctrl,.prompt-choice,.turn-btn{border:1px solid rgba(108,71,33,.18);color:var(--ink);cursor:pointer;transition:transform 120ms ease,box-shadow 120ms ease,background 120ms ease}.ctrl,.prompt-choice{background:linear-gradient(180deg,#fef7eb 0%,#f2e2c4 100%);padding:9px 12px;border-radius:12px}.ctrl:hover,.prompt-choice:hover,.turn-btn:hover{transform:translateY(-1px);box-shadow:0 8px 20px rgba(85,49,22,.12)}
.turn-list{display:flex;flex-direction:column;gap:8px;max-height:calc(100vh - 220px);overflow:auto}.turn-btn{width:100%;text-align:left;padding:11px 12px;border-radius:14px;background:rgba(255,255,255,.7)}.turn-btn.active{background:linear-gradient(180deg,#f5d89d,#eab868)}
.prompt-open{border-color:rgba(178,74,42,.28);box-shadow:0 18px 40px rgba(178,74,42,.14)}.prompt-layout{display:grid;grid-template-columns:1.1fr .9fr;gap:14px}.stack,.feed,.kv,.actions,.plist,.legend,.summary{display:flex;flex-direction:column;gap:8px}
.card,.event,.hint,.kv-item{padding:10px 12px;border-radius:12px;border:1px solid var(--line);background:rgba(255,255,255,.66)}.event strong{color:#7d2e17}.prompt-choice{width:100%;text-align:left}
.board-shell{display:grid;grid-template-columns:minmax(0,1fr) 220px;gap:14px}.board{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px}.tile{min-height:118px;border-radius:18px;border:1px solid rgba(84,52,19,.16);padding:10px;display:flex;flex-direction:column;justify-content:space-between;position:relative;overflow:hidden;background:linear-gradient(180deg,rgba(255,255,255,.92),rgba(245,239,229,.8))}.tile::after{content:"";position:absolute;inset:auto 0 0 0;height:6px;background:rgba(65,46,24,.08)}.tile.focus{outline:3px solid rgba(178,74,42,.22)}
.tile-top{display:flex;justify-content:space-between;align-items:flex-start;gap:8px}.tile-index{font-size:12px;color:var(--muted)}.tile-kind{margin-top:4px;font-size:14px;font-weight:700}.owner,.pawn{display:inline-flex;align-items:center;justify-content:center;color:#fff;font-size:11px;font-weight:700}.owner{min-width:28px;height:28px;border-radius:50%}.pawn-row{display:flex;flex-wrap:wrap;gap:6px}.pawn{min-width:28px;height:28px;border-radius:999px;box-shadow:0 8px 18px rgba(0,0,0,.12);animation:pulse 1.6s ease-in-out infinite}@keyframes pulse{0%,100%{transform:translateY(0)}50%{transform:translateY(-2px)}}
.tile-meta{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}.tile-stat,.pstat{padding:6px 8px;border-radius:10px;background:rgba(255,255,255,.55);border:1px solid rgba(84,52,19,.1)}.tile-stat .k,.pstat .k{color:var(--muted);font-size:11px}.tile-stat .v,.pstat .v{margin-top:2px;font-size:13px;font-weight:700}
.player{border:1px solid var(--line);border-left-width:7px;border-radius:18px;padding:12px;background:rgba(255,255,255,.72)}.player.actor{box-shadow:inset 0 0 0 2px rgba(178,74,42,.22)}.ptop{display:flex;justify-content:space-between;align-items:center;gap:10px}.pname{font-size:18px;font-weight:700}.pchar{margin-top:2px;color:var(--muted);font-size:13px}.pgrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:12px}.pills{display:flex;flex-wrap:wrap;gap:6px;margin-top:10px}.pill{padding:5px 8px;border-radius:999px;font-size:11px;border:1px solid rgba(84,52,19,.1);background:rgba(255,255,255,.75)}
@media (max-width:1200px){.grid{grid-template-columns:240px minmax(0,1fr)}.players{grid-column:1 / -1}}@media (max-width:920px){.page{padding:10px}.grid,.stats,.prompt-layout,.board-shell,.pgrid{grid-template-columns:1fr}.board{grid-template-columns:repeat(2,minmax(0,1fr))}.turn-list{max-height:none}}
</style>
</head>
<body>
<div class="page"><div class="grid">
<aside class="col"><section class="panel"><div class="head"><div><div class="eyebrow">Timeline</div><h2 class="title" style="font-size:20px">Turn Navigation</h2></div><div class="chip" id="status">Connecting...</div></div><div class="body"><div class="controls" style="margin-bottom:10px"><button class="ctrl" onclick="goFirst()">First</button><button class="ctrl" onclick="goPrev()">Prev</button><button class="ctrl" onclick="followLatest()">Follow</button></div><div class="turn-list" id="turn-list"></div></div></section></aside>
<main class="main">
<section class="panel"><div class="head"><div><div class="eyebrow">Live Match</div><h1 class="title" id="title">GPT Live Spectator</h1></div><div class="mini" id="header-chip"><strong>sync</strong> waiting</div></div><div class="body"><div class="helper" id="subtitle">Waiting for projection...</div><div class="stats" style="margin-top:14px"><div class="stat"><div class="k">Round</div><div class="v" id="stat-round">-</div></div><div class="stat"><div class="k">Turn</div><div class="v" id="stat-turn">-</div></div><div class="stat"><div class="k">Actor</div><div class="v" id="stat-actor">-</div></div><div class="stat"><div class="k">Waiting</div><div class="v" id="stat-waiting">No</div></div></div></div></section>
<section class="panel" id="prompt-panel"><div class="head"><div><div class="eyebrow">Decision</div><h2 class="title" style="font-size:20px">Prompt Console</h2></div><div class="mini" id="prompt-status">No active prompt.</div></div><div class="body"><div class="helper" id="prompt-submit-status"></div><div class="prompt-layout"><div id="prompt-body"></div><div id="prompt-side"></div></div></div></section>
<section class="panel"><div class="head"><div><div class="eyebrow">Board</div><h2 class="title" style="font-size:20px">Public Map</h2></div><div class="mini" id="board-meta"><strong>F</strong> -</div></div><div class="body"><div class="board-shell"><div class="board" id="board"></div><div class="stack"><div class="summary" id="board-summary"></div><div class="legend" id="board-legend"></div></div></div></div></section>
<section class="panel"><div class="head"><div><div class="eyebrow">Feed</div><h2 class="title" style="font-size:20px">Recent Public Events</h2></div></div><div class="body"><div class="feed" id="events"></div></div></section>
</main>
<aside class="col players"><section class="panel"><div class="head"><div><div class="eyebrow">Roster</div><h2 class="title" style="font-size:20px">Player Panels</h2></div></div><div class="body"><div class="plist" id="players"></div></div></section></aside>
</div></div>
<script>
const PLAYER_COLORS=["#4e8ef7","#e85d5d","#5dbf5d","#f0a030"];
const ZONE_TONES={red:"linear-gradient(180deg, rgba(255,230,225,.96), rgba(248,195,184,.92))",blue:"linear-gradient(180deg, rgba(226,239,255,.96), rgba(189,213,248,.92))",green:"linear-gradient(180deg, rgba(233,250,230,.96), rgba(191,231,187,.92))",yellow:"linear-gradient(180deg, rgba(255,248,217,.96), rgba(241,220,149,.92))",purple:"linear-gradient(180deg, rgba(244,232,252,.96), rgba(214,190,234,.92))",orange:"linear-gradient(180deg, rgba(255,238,220,.96), rgba(241,198,146,.92))"};
let turns=[];let currentIndex=0;let autoFollow=true;let promptState=null;let latestPayload=null;
function safeArray(v){return Array.isArray(v)?v:[]} function playerColor(id){return id==null?"#8c7b6a":PLAYER_COLORS[(id-1)%PLAYER_COLORS.length]} function zoneTone(z){if(!z)return"linear-gradient(180deg, rgba(255,255,255,.92), rgba(245,239,229,.8))";return ZONE_TONES[String(z).toLowerCase()]||"linear-gradient(180deg, rgba(255,255,255,.92), rgba(245,239,229,.8))"}
function turnLabel(t){return `Turn ${t.turn_index} / Round ${t.round_index} / P${t.acting_player_id ?? '-'}`}
function promptTitle(type){const labels={movement:"Movement Choice",purchase_decision:"Purchase Decision",draft_choice:"Draft Pick",character_choice:"Final Character",lap_reward:"Lap Reward",mark_target:"Mark Target",coin_placement:"Coin Placement",doctrine_relief:"Doctrine Relief",geo_bonus:"Geo Bonus",active_flip:"Active Flip",burden_exchange:"Burden Exchange"};return labels[type]||type}
function promptHint(type){const hints={movement:"Choose whether to roll normally or lock movement using dice cards.",purchase_decision:"Landing purchase prompt. Public tile cost and your current cash are shown.",draft_choice:"Pick one card from the offered draft set.",character_choice:"Choose the final character identity from drafted cards.",lap_reward:"Select the public lap reward that best fits the current board state.",mark_target:"Choose a legal future-turn target or pass if allowed.",coin_placement:"Place a score coin on one of your valid owned tiles.",doctrine_relief:"Relieve one legal target or pass.",geo_bonus:"Choose which public resource bonus to take.",active_flip:"Choose which drafted card to flip active, or pass.",burden_exchange:"Decide whether to exchange burden when the engine offers it."};return hints[type]||"Resolve the currently open prompt."}
function formatContextEntries(ctx){return Object.entries(ctx||{}).map(([k,v])=>`<div class="kv-item"><strong>${k}</strong><div class="meta">${Array.isArray(v)?v.join(", "):String(v)}</div></div>`).join("")}

function renderTurnList(){const root=document.getElementById("turn-list");root.innerHTML="";turns.forEach((turn,index)=>{const btn=document.createElement("button");btn.className="turn-btn"+(index===currentIndex?" active":"");const waitLabel=promptState&&promptState.status==="open"&&promptState.prompt&&turn.acting_player_id===promptState.prompt.player_id?" | input open":"";btn.innerHTML=`<div><strong>${turnLabel(turn)}</strong></div><div class="meta">weather=${turn.round_weather_name||"-"}${waitLabel}</div>`;btn.onclick=()=>{autoFollow=false;goTo(index)};root.appendChild(btn)})}
function renderEvents(turn){const root=document.getElementById("events");root.innerHTML="";const prelude=safeArray(turn.round_prelude_events);if(prelude.length){const title=document.createElement("div");title.className="hint";title.innerHTML=`<strong>Round Prelude</strong><div class="meta">weather=${turn.round_weather_name||"-"}</div>`;root.appendChild(title);prelude.forEach((event)=>{const row=document.createElement("div");row.className="event";row.innerHTML=`<strong>[${event.actor}] ${event.type}</strong><div class="meta">${event.detail}</div>`;root.appendChild(row)})}const events=safeArray(turn.events);if(!events.length){const empty=document.createElement("div");empty.className="event";empty.innerHTML="<strong>No public key events.</strong><div class='meta'>This turn has no surfaced key events yet.</div>";root.appendChild(empty);return}events.forEach((event)=>{const row=document.createElement("div");row.className="event";row.innerHTML=`<strong>[${event.actor}] ${event.type}</strong><div class="meta">${event.detail}</div>`;root.appendChild(row)})}
function renderBoard(turn){const board=turn.board||{};const tiles=safeArray(board.tiles);const root=document.getElementById("board");const summary=document.getElementById("board-summary");const legend=document.getElementById("board-legend");const actor=safeArray(turn.players).find((p)=>p.player_id===turn.acting_player_id);const actorTile=actor?actor.position:null;document.getElementById("board-meta").innerHTML=`<strong>F</strong> ${board.f_value ?? "?"} <strong>Marker</strong> P${board.marker_owner_player_id ?? "-"}`;root.innerHTML="";for(let i=0;i<40;i++){const tile=tiles[i]||{};const el=document.createElement("div");el.className="tile"+(actorTile===i?" focus":"");el.style.background=zoneTone(tile.zone_color);const owner=tile.owner_player_id;const ownerBadge=owner!=null?`<div class="owner" style="background:${playerColor(owner)};">P${owner}</div>`:`<div class="owner" style="background:#a59789;">-</div>`;const pawns=safeArray(tile.pawn_player_ids).map((id)=>`<span class="pawn" style="background:${playerColor(id)};">P${id}</span>`).join("");el.innerHTML=`<div class="tile-top"><div><div class="tile-index">#${i} | ${tile.zone_color || "neutral"}</div><div class="tile-kind">${tile.tile_kind || "?"}</div></div>${ownerBadge}</div><div class="tile-meta"><div class="tile-stat"><div class="k">Buy</div><div class="v">${tile.purchase_cost != null ? tile.purchase_cost : "-"}</div></div><div class="tile-stat"><div class="k">Rent</div><div class="v">${tile.rent_cost != null ? tile.rent_cost : "-"}</div></div><div class="tile-stat"><div class="k">Coin</div><div class="v">${tile.score_coin_count ?? 0}</div></div><div class="tile-stat"><div class="k">Block</div><div class="v">${tile.block_id ?? "-"}</div></div></div><div class="pawn-row">${pawns || '<span class="meta">no pawns</span>'}</div>`;root.appendChild(el)}const owned=tiles.filter((t)=>t&&t.owner_player_id!=null).length;const occupied=tiles.filter((t)=>t&&safeArray(t.pawn_player_ids).length>0).length;summary.innerHTML=`<div class="card"><strong>Owned tiles</strong><div class="meta">${owned} / 40 publicly owned</div></div><div class="card"><strong>Occupied tiles</strong><div class="meta">${occupied} currently have pawns</div></div><div class="card"><strong>Current actor tile</strong><div class="meta">${actorTile != null ? "#" + actorTile : "-"}</div></div>`;legend.innerHTML=PLAYER_COLORS.map((color,index)=>`<div class="card"><strong style="color:${color}">P${index+1}</strong><div class="meta">owner / pawn color</div></div>`).join("")}
function renderPlayers(turn,prompt){const root=document.getElementById("players");root.innerHTML="";safeArray(turn.players).forEach((player)=>{const card=document.createElement("div");const isActor=player.player_id===turn.acting_player_id;const isWaiting=prompt&&player.player_id===prompt.player_id;card.className="player"+(isActor?" actor":"");card.style.borderLeftColor=playerColor(player.player_id);const effects=safeArray(player.public_effects);const tricks=safeArray(player.public_tricks);const burdens=safeArray(player.burden_summary);const owned=safeArray(player.owned_tile_indices);card.innerHTML=`<div class="ptop"><div><div class="pname">P${player.player_id}</div><div class="pchar">${player.character || "?"}</div></div><div class="mini"><strong>${player.alive ? "alive":"out"}</strong> ${isWaiting ? "waiting input" : isActor ? "acting" : "idle"}</div></div><div class="pgrid"><div class="pstat"><div class="k">Cash</div><div class="v">${player.cash}</div></div><div class="pstat"><div class="k">Shards</div><div class="v">${player.shards}</div></div><div class="pstat"><div class="k">Score Coins</div><div class="v">${player.hand_score_coins} hand / ${player.placed_score_coins} placed</div></div><div class="pstat"><div class="k">Position</div><div class="v">#${player.position}</div></div><div class="pstat"><div class="k">Tiles</div><div class="v">${player.owned_tile_count}</div></div><div class="pstat"><div class="k">Mark</div><div class="v">${player.mark_status}${player.pending_mark_source ? " from P" + player.pending_mark_source : ""}</div></div></div><div class="pills">${(effects.length?effects:["no public effects"]).map((x)=>`<span class="pill">${x}</span>`).join("")}</div><div class="pills">${(tricks.length?tricks:["no public tricks"]).map((x)=>`<span class="pill">${x}</span>`).join("")}<span class="pill">hidden tricks ${player.hidden_trick_count}</span></div><div class="pills">${(burdens.length?burdens:["no burden"]).map((x)=>`<span class="pill">${x}</span>`).join("")}</div><div class="helper" style="margin-top:10px">owned tiles: ${owned.length ? owned.join(", ") : "-"}</div>`;root.appendChild(card)})}
function renderPrompt(turn){const panel=document.getElementById("prompt-panel");const status=document.getElementById("prompt-status");const submit=document.getElementById("prompt-submit-status");const body=document.getElementById("prompt-body");const side=document.getElementById("prompt-side");body.innerHTML="";side.innerHTML="";submit.textContent="";if(!promptState||promptState.status!=="open"||!promptState.prompt){panel.classList.remove("prompt-open");status.textContent="No active prompt.";body.innerHTML='<div class="hint"><strong>Idle</strong><div class="meta">No human-facing prompt is open right now.</div></div>';side.innerHTML='<div class="hint"><strong>Mode</strong><div class="meta">The match is currently advancing without waiting for browser input.</div></div>';return}panel.classList.add("prompt-open");const prompt=promptState.prompt;status.textContent=`P${prompt.player_id} | ${promptTitle(prompt.decision_type)}`;const acting=safeArray(turn.players).find((player)=>player.player_id===prompt.player_id);body.innerHTML=`<h3 style="margin:0 0 6px;font-size:20px">${promptTitle(prompt.decision_type)}</h3><div class="hint"><strong>Seat P${prompt.player_id}</strong><div class="meta">${promptHint(prompt.decision_type)}</div></div><div class="kv" style="margin-top:10px">${formatContextEntries(prompt.public_context)}</div><div class="actions" style="margin-top:12px" id="prompt-actions"></div>`;side.innerHTML=`<div class="card"><strong>Player Snapshot</strong><div class="meta">${acting ? `${acting.character || "?"} | cash ${acting.cash} | shards ${acting.shards} | pos #${acting.position}` : "No matching snapshot"}</div></div><div class="card"><strong>Deadline</strong><div class="meta">${prompt.deadline_mode || "-"}</div></div><div class="card"><strong>Choice Count</strong><div class="meta">${safeArray(prompt.choices).length}${prompt.can_pass ? " + pass" : ""}</div></div>`;const actions=document.getElementById("prompt-actions");safeArray(prompt.choices).forEach((choice)=>{const button=document.createElement("button");button.className="prompt-choice";button.innerHTML=`<strong>${choice.label}</strong><div class="meta">key=${choice.key}</div>`;button.onclick=async()=>{const ok=await submitPromptChoice(prompt.prompt_id,choice.key);if(ok){submit.textContent=`submitted: ${choice.key}`}};actions.appendChild(button)});if(prompt.can_pass){const pass=document.createElement("button");pass.className="prompt-choice";pass.innerHTML="<strong>Pass</strong><div class='meta'>submit null / no choice</div>";pass.onclick=async()=>{const ok=await submitPromptChoice(prompt.prompt_id,null);if(ok){submit.textContent="submitted: pass"}};actions.appendChild(pass)}}
function renderCurrent(){if(!turns.length){document.getElementById("events").innerHTML='<div class="helper">Waiting for turns...</div>';document.getElementById("players").innerHTML='<div class="helper">No player snapshots yet.</div>';document.getElementById("board").innerHTML="";return}const turn=turns[currentIndex];const prompt=promptState&&promptState.status==="open"?promptState.prompt:null;document.getElementById("title").textContent=turnLabel(turn);document.getElementById("subtitle").textContent=`weather=${turn.round_weather_name || "-"} | events=${safeArray(turn.events).length} | skipped=${turn.skipped ? "yes":"no"}`;document.getElementById("header-chip").innerHTML=`<strong>${latestPayload ? latestPayload.status : "?"}</strong> ${autoFollow ? "auto-follow":"manual view"}`;document.getElementById("stat-round").textContent=String(turn.round_index ?? "-");document.getElementById("stat-turn").textContent=String(turn.turn_index ?? "-");document.getElementById("stat-actor").textContent=turn.acting_player_id ? `P${turn.acting_player_id}` : "-";document.getElementById("stat-waiting").textContent=prompt ? `P${prompt.player_id}` : "No";renderEvents(turn);renderBoard(turn);renderPlayers(turn,prompt);renderTurnList();renderPrompt(turn)}
function goTo(index){if(index<0||index>=turns.length)return;currentIndex=index;renderCurrent()} function goFirst(){autoFollow=false;goTo(0)} function goPrev(){autoFollow=false;goTo(currentIndex-1)} function followLatest(){autoFollow=true;if(turns.length)goTo(turns.length-1)}
async function submitPromptChoice(promptId,choiceKey){try{const response=await fetch("/api/prompt-response",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt_id:promptId,choice_key:choiceKey})});if(!response.ok){const payload=await response.json().catch(()=>({}));const msg=payload.error ? payload.error : `HTTP ${response.status}`;document.getElementById("prompt-submit-status").textContent=`submit failed: ${msg}`;return false}return true}catch(error){document.getElementById("prompt-submit-status").textContent=`submit failed: ${error}`;return false}}
async function refresh(){try{const [stateResponse,promptResponse]=await Promise.all([fetch(`live_state.json?ts=${Date.now()}`,{cache:"no-store"}),fetch(`prompt_state.json?ts=${Date.now()}`,{cache:"no-store"})]);if(!stateResponse.ok){document.getElementById("status").textContent=`HTTP ${stateResponse.status}`;return}latestPayload=await stateResponse.json();promptState=promptResponse.ok ? await promptResponse.json() : null;const projection=latestPayload.projection||{};turns=((projection.session||{}).turns||[]).map((turn)=>({turn_index:turn.turn_index,round_index:turn.round_index,acting_player_id:turn.acting_player_id,skipped:turn.skipped,players:(turn.snapshot||{}).players||[],board:(turn.snapshot||{}).board||{},events:(turn.key_events||[]).map((event)=>({actor:event.acting_player_id!=null?`P${event.acting_player_id}`:"-",type:event.event_type,detail:event.public_summary||event.summary||event.event_type})),round_weather_name:"",round_prelude_events:[]}));const rounds=((projection.session||{}).rounds||[]);const roundMap=new Map(rounds.map((round)=>[round.round_index,round]));turns=turns.map((turn)=>{const round=roundMap.get(turn.round_index);return {...turn,round_weather_name:round ? round.weather_name : "",round_prelude_events:round ? (round.prelude_events||[]).filter((event)=>event.event_type!=="round_start").map((event)=>({actor:event.acting_player_id!=null?`P${event.acting_player_id}`:"-",type:event.event_type,detail:event.public_summary||event.summary||event.event_type})) : []}});const summary=latestPayload.summary||{};document.getElementById("status").textContent=`status=${latestPayload.status} | events=${summary.total_events ?? 0} | turns=${turns.length}`;if(autoFollow&&turns.length){currentIndex=turns.length-1}else if(currentIndex>=turns.length){currentIndex=Math.max(0,turns.length-1)}renderCurrent()}catch(error){document.getElementById("status").textContent=`refresh failed: ${error}`}}
refresh();setInterval(refresh,1000);
</script>
</body>
</html>
"""


def render_live_html() -> str:
    return LIVE_HTML_TEMPLATE
